import React, { useState } from 'react';
import { Check, Copy, Globe } from 'lucide-react';
import { SourcePreviews } from './SourcePreviews';

const Message = ({ msg, streaming }) => {
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState(false);
  const copy = async () => {
    try { await navigator.clipboard.writeText(msg.content); setCopied(true); setCopyError(false); }
    catch { setCopyError(true); }
  };
  if (msg.role === 'user') return (
    <div className="ares-in flex justify-end mb-6" data-testid={`message-${msg.id}`}>
      <div className="ares-user-bubble">
        {msg.image_b64 && <img src={`data:image/png;base64,${msg.image_b64}`} alt="Your attachment" className="mb-2 max-h-[180px] max-w-full object-contain" data-testid={`message-image-${msg.id}`} />}
        <span className="ares-message-text whitespace-pre-wrap" data-testid={`message-content-${msg.id}`}>{msg.content}</span>
      </div>
    </div>
  );

  return (
    <div className="ares-in ares-assistant-message" data-testid={`message-${msg.id}`}>
      <div className="ares-avatar" aria-hidden="true">A</div>
      <div className="ares-assistant-content">
        <div className="ares-assistant-bubble">
          {msg.image_b64 && <img src={`data:image/png;base64,${msg.image_b64}`} alt="Generated by Ares" className="mb-2 w-full max-w-[420px] object-contain" data-testid={`message-image-${msg.id}`} />}
          {msg.searching && !msg.content && <p className="text-xs flex items-center gap-2" role="status" data-testid={`message-searching-${msg.id}`} style={{ color: 'var(--ares-text-dim)' }}><Globe size={13} className="animate-spin shrink-0" style={{ animationDuration: '2.4s' }} />Searching the live web...</p>}
          <div className="ares-message-text whitespace-pre-wrap" data-testid={`message-content-${msg.id}`}>{msg.content}{streaming && <span className="ares-caret" aria-label="Generating response">▍</span>}</div>
        </div>
        {!!msg.citations?.length && <SourcePreviews citations={msg.citations} messageId={msg.id} />}
        {!streaming && msg.content && <div className="flex items-center gap-2 mt-1">
          <button onClick={copy} className="ares-btn ares-copy-button" title="Copy response" data-testid={`message-copy-${msg.id}`}>{copied ? <Check size={13} /> : <Copy size={13} />}<span>{copied ? 'Copied' : 'Copy'}</span></button>
          {copyError && <span className="text-xs" role="alert" data-testid={`message-copy-error-${msg.id}`}>Could not copy. Try again.</span>}
        </div>}
      </div>
    </div>
  );
};

export default Message;